version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - db-data:/code/database.db
      - pdf_data:/code/pdf_files
  web:
    build:
      context: .
      dockerfile: ./pdf-reader/Dockerfile
    env_file:
      - .env
    depends_on:
      - api
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "1339:80"
    depends_on:
      - web
      - api
volumes:
  db-data:
  pdf_data:
